name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "ThriceCola"
          reponame: "thricecola.github.io"
          token: ${{ secrets.GITHUB_TOKEN }} # Use default token with enhanced permissions
